name: Build Static Site

on: [push]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                hugo-version: '0.119.0'
            - name: Install dependencies
              run: yarn
            - run: npm run build
            - name: Save
              uses: actions/upload-artifact@v4
              with:
                name: public
                path: |
                  public
            